Repository DougMidgley/SFMC-SDK, pull requests merged in 2022-05, with the labels that each got.

#103 Support REST request/response Logging w/ test
  lib/rest.js
  test/resources/auth.json
  test/rest.test.js
Labels: enhancement

#107 Bug/simpleobjectvalidation
  lib/rest.js
  lib/util.js
  test/resources/rest.json
  test/rest.test.js
Labels: bug

#108 Standardized Error Messages returned where possible
  lib/auth.js
  lib/rest.js
  lib/soap.js
  lib/util.js
  package.json
  test/auth.test.js
  test/rest.test.js
  test/soap.test.js
Labels: enhancement

#105 Release May 2022
  lib/auth.js
  lib/rest.js
  lib/soap.js
  lib/util.js
  package-lock.json
  package.json
  test/auth.test.js
  test/resources/auth.json
  test/resources/rest.json
  test/rest.test.js
  test/soap.test.js
Labels: release, major
