Repository DougMidgley/SFMC-SDK, pull requests merged in 2023-01, with the labels that each got.

#153 #152 call onLoop cb in Rest.getBulk
  lib/rest.js
Labels: chore

#151 #150: ensure rest API errors print the targeted endpoint
  lib/rest.js
  lib/util.js
Labels: chore

#157 Bump dependencies
  .github/workflows/codeql-analysis.yml
  package-lock.json
  package.json
Labels: dependencies

#156 Develop
  .github/workflows/codeql-analysis.yml
  lib/rest.js
  lib/soap.js
  lib/util.js
  package-lock.json
  package.json
  test/resources/soap.json
  test/soap.test.js
Labels: release

#168 #167: always attach "endpoint" to errors thrown in rest.js
  lib/rest.js
  lib/util.js
Labels: chore

#170 #169 allow "items" and "definitions" as iterator fields
  lib/rest.js
Labels: bug

#172 #171: fix for bad count value from transactional message api
  lib/rest.js
Labels: bug

#174 Bug/173 fix accumulator param passed to onloop
  lib/rest.js
  lib/soap.js
Labels: bug

#177 February 2023 Release
  lib/rest.js
  lib/soap.js
  lib/util.js
  package-lock.json
  package.json
Labels: release
